### ISSUE TITLE
Enable Running Ballerina Service and Main Docker images

### ISSUE THREAD

**Issue by chamilad** [ballerina-lang/container-support#26]

**Comment by chamilad** [comment]
This feature is implemented in the branch `future` [1]. Some points about the implementation are, 

1. The implementation depends on `1.2-SNAPSHOT` version of `fabric8/docker-client`. This should be updated as soon as a new release is done.
2. Currently, no logs can be collected for Main container runs, because of a possible bug in the library.
3. Because of complexity in implementation compared to potential usage, running containers on a remote Docker daemon is currently disabled.

[1] - https://github.com/ballerinalang/container-support/tree/future

**Comment by chamilad** [comment]
`fabric8/docker-client` has now released the above fix needed in version `1.2.2` [1]. The dependency version should be updated in the root POM (`ballerinalang/ballerina/pom.xml`).


[1] - https://github.com/fabric8io/docker-client/tree/v1.2.2

**Comment by uthaiyashankar** [comment]
New docker implementation is in https://github.com/ballerinax/docker
