### ISSUE TITLE
Handle image Labels in resulting images

### ISSUE THREAD

**Issue by chamilad** [ballerina-lang/container-support#31]
When Docker image Labels are introduced to the Ballerina base image, they should be overridden by the child images for clarity. This should especially be done for `org.label-schema.build-date`. Furthermore, it should be made possible to pass a list of labels to be written to the new image. These can be passed as a set of key value pairs than can possibly override crucial information like `org.label-schema.description`, `org.label-schema.vcs-ref` etc.

**Comment by lakwarus** [comment]
This is invalid with new docker support ballerina. Please see https://github.com/ballerinax/docker

**Comment by uthaiyashankar** [comment]
Resolving as per last comment
