### ISSUE TITLE
Ballerina Container Improvements

### ISSUE THREAD

**Issue by TylerJewell** [ballerina-lang/container-support#40]
This is a collection of thoughts based upon an investigation of Ballerina's container tools and experiences that we have had from working with other Docker containers. These are a collection of tasks that could be packaged into a pull request for consideration.

Generally, the goal of the image would be to have it act as a faster alternative to getting started with Ballerina vs. the process of installing binaries. It has to feel like a simple syntax that is similar to what would happen if the user had installed the native binaries themselves.

1. The primary Ballerina docker image is making assumptions about the execution model.  So it is assuming that there is a `ballerina run` command, which makes the image somewhat disconnected from the expected development lifecycle that is documented on the web site, ie `ballerina run main` is an expected syntax, but the Docker image would have the end user provide a different syntax.  Consistent with other language Docker images, we should expose the normal command line syntax so that using the Docker image is a faster alternative to installing the binaries.

2.  The volume mount can be simplified to just `:/ballerina` instead of `:/ballerina/files`.  We can add in checks for testing the validity of this volume mount and give a helpful error message if this mount is not there or misconfigured.

3. We should have two separate images to follow best practices - one that is stateless and another one for just running ballerina as a server.  The running ballerina as a server with ports would be a secondary image that is not directly launchable by end users, but the ballerinalang/ballerina primary image can launch it if necessary.  You could also have a separate image for the composer, or it could have both the composer and server at the same time.

4. The `ballerina docker` sytnax can be built directly into the `ballerinalang/ballerina` Docker image. There is no need to have it be a separate workflow.  It can be a single docker image that provides this capability.  Since this would be in a single image, we can then use Docker introspection to detect valid `DOCKER_HOST` or a unix socket mount instead of passing those parameters as additional parameters on the command line.  Also, since `:/ballerina` has to always be volume mounted, the source packages that need to be converted into Docker iamges can be simplified.

**Comment by chamilad** [comment]
Thanks @TylerJewell for these suggestions! These are wonderful improvements to be done. I will setup a list of subtasks TBD soon.

**Comment by lakwarus** [comment]
We have new implementation for docker support for Ballerina. All mention improvements are achieved by deferent way with the annotation based docker support. Please see https://github.com/ballerinax/docker

**Comment by uthaiyashankar** [comment]
Resolving as per last comment.
