### ISSUE TITLE
ballerinalang/ballerina Docker images should be uploaded for each release

### ISSUE THREAD

**Issue by chamilad** [ballerina-lang/container-support#49]
For each release, `ballerinalang/ballerina` [1] and `ballerina/ballerina` [2] public Docker images should be pushed. They should be tagged with the release version, and the tag `latest` should point to the latest released image. 

[1] - https://hub.docker.com/r/ballerinalang/ballerina/tags/
[2] - https://hub.docker.com/r/ballerina/ballerina/tags/

**Comment by uthaiyashankar** [comment]
This repo is not used now. New docker implementation is in https://github.com/ballerinax/docker
