### ISSUE TITLE
Error messages should be more descriptive

### ISSUE THREAD

**Issue by chamilad** [ballerina-lang/container-support#53]
As of now, any error that blocks building the Docker images results in the following message.

```
ballerina: Docker image build failed for image image1:latest
```
The underlying issue could be one of many, including the absence of the base image (especially for `*-SNAPSHOT` versions) and using a user with no privileges over the docker client. These error messages should correctly reflect the underlying error.

**Comment by djkevincr** [comment]
PR https://github.com/ballerina-lang/container-support/pull/69 addresses this. Hence closing.
