### ISSUE TITLE
Should the default command be "ballerina run" or just "ballerina"

### ISSUE THREAD

**Issue by pzfreo** [ballerina-lang/container-support#83]
It would be nice to be able to use the docker image to build as well as run.
At the moment, the image entrypoint always does run. 
It might be more useful to change it to just do ballerina and expect the user to supply run/build/help/etc.

**Comment by lakwarus** [comment]
This way of docker support for ballerina going to deprecate now. We are having two main docker based images for ballerina. One is with ballerina runtime which can be used with ballerina run cmd. Other is with ballerina-tools which can be used with ballerina build cmd. Please see https://hub.docker.com/r/ballerina/

New docker support for ballerina can be found in https://github.com/ballerinax/docker

**Comment by uthaiyashankar** [comment]
Resolving as per last comment.
